-- Precomputed per-property violation summaries for the public SEO landing
-- pages (/p/{borough}/{slug}).
--
-- These pages exist to be crawled, and a crawl is all cache misses: a bot
-- walking 50k properties against the live Socrata path would be 200k+ API
-- calls against a rate-limited source. So the landing pages read only this
-- table, refreshed by scripts/refresh-seo-summaries.ts on a nightly schedule.
-- The paid /report/{bbl} still generates live and is unaffected.
--
-- Rows exist ONLY for properties with at least one violation. A clean property
-- has no unique content to rank for, and generating ~858k near-identical
-- pages is the textbook auto-generated-thin-content pattern that risks a
-- sitewide quality demotion rather than just failing to rank.

create table if not exists property_seo_summaries (
  bbl              char(10) primary key references properties (bbl) on delete cascade,
  -- URL slug, e.g. '123-main-st-10001'. Generated by the refresh script, not
  -- derived at request time: properties.address_normalized is NOT unique
  -- across lots, so collisions are resolved with a numeric suffix and the
  -- winner has to be remembered. Unique per borough, not globally — the
  -- borough is a separate path segment.
  slug             text not null,
  -- Lowercased borough for the URL ('manhattan', 'staten-island').
  borough_slug     text not null,

  dob_total        integer not null default 0,
  hpd_total        integer not null default 0,
  -- ECB and OATH are collapsed into one figure. ~82.6% of ECB summonses also
  -- appear in the OATH docket, so reporting them separately double-counts.
  ecb_oath_total   integer not null default 0,

  open_violations  integer not null default 0,
  total_violations integer not null default 0,

  computed_at      timestamptz not null default now(),

  constraint property_seo_slug_unique unique (borough_slug, slug),
  constraint property_seo_counts_nonneg check (
    dob_total >= 0 and hpd_total >= 0 and ecb_oath_total >= 0
    and open_violations >= 0 and total_violations >= 0
  ),
  -- The table's entire reason to exist; a zero-violation row would be a thin
  -- page with nothing to say.
  constraint property_seo_has_violations check (total_violations > 0)
);

-- Borough hub pages list properties by violation count, and the sitemap
-- chunks by borough. Both are covered by this one index.
create index if not exists property_seo_borough_rank_idx
  on property_seo_summaries (borough_slug, total_violations desc, bbl);

-- ---------------------------------------------------------------------------
-- RLS: these rows are the public content of the landing pages, so they are
-- anon-readable exactly like `properties`. Writes stay service-role only.
--
-- Note this is deliberately the opposite posture from `violations`, which is
-- service-role-read: that table holds per-violation detail (the paid product),
-- whereas this one holds only the counts already shown on a public page.
-- ---------------------------------------------------------------------------
alter table property_seo_summaries enable row level security;

drop policy if exists property_seo_summaries_read on property_seo_summaries;
create policy property_seo_summaries_read on property_seo_summaries
  for select using (true);
